name: Referee-system

services:
  app:
    build: .
    image: ref-sys-image
    container_name: ref-sys-container
    command: /app/entrypoint.sh
    ports:
      - "8000:8000"
    volumes:
      - "./backend:/app"
    depends_on:
      - postgres
      - redis
  
  postgres:
    image: postgres
    container_name: postgres-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  redis:
    image: "redis:alpine"
    container_name: redis-container
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  celery:
    image: ref-sys-image
    container_name: celery-container
    command: celery -A ref_sys worker -E -l info
    volumes:
      - "./backend:/app"
    depends_on:
      - app
      - postgres
      - redis
  
  flower:
    image: ref-sys-image
    container_name: flower-container
    command: celery -A ref_sys flower --basic_auth=admin:admin
    ports:
      - "5555:5555"
    depends_on:
      - redis
  
  beat:
    image: ref-sys-image
    container_name: beat-container
    command: celery -A ref_sys beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - "./backend:/app"
    depends_on:
      - redis
      - app

volumes:
  postgres_data:
  redis_data: