# Generated by Django 5.1.4 on 2024-12-22 15:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("referee", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examination",
            name="date",
            field=models.DateField(verbose_name="Examination Date"),
        ),
        migrations.AlterField(
            model_name="examination",
            name="note_external",
            field=models.TextField(blank=True, verbose_name="Note (external)"),
        ),
        migrations.AlterField(
            model_name="examination",
            name="note_internal",
            field=models.TextField(blank=True, verbose_name="Note (internal)"),
        ),
        migrations.AlterField(
            model_name="referee",
            name="dob",
            field=models.DateField(blank=True, null=True, verbose_name="Date of Birth"),
        ),
        migrations.AlterField(
            model_name="referee",
            name="iban",
            field=models.CharField(blank=True, max_length=34, verbose_name="IBAN"),
        ),
    ]
