# Generated by Django 5.1.4 on 2024-12-23 15:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("referee", "0002_alter_examination_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RefereeRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "order",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(-100),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
            ],
            options={
                "verbose_name": "Role",
                "verbose_name_plural": "Roles",
                "ordering": ["order", "name"],
            },
        ),
        migrations.AddField(
            model_name="referee",
            name="mobile",
            field=models.CharField(
                blank=True, max_length=25, null=True, verbose_name="Mobile phone number"
            ),
        ),
        migrations.AddField(
            model_name="referee",
            name="phone",
            field=models.CharField(
                blank=True, max_length=25, null=True, verbose_name="Phone number"
            ),
        ),
    ]
