# Generated by Django 5.1.4 on 2024-12-23 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("referee", "0003_refereerole_referee_mobile_referee_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examination",
            name="candidate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exams",
                to="referee.referee",
                verbose_name="Candidate",
            ),
        ),
        migrations.AlterField(
            model_name="examination",
            name="license",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="exams",
                to="referee.refereelicense",
                verbose_name="License",
            ),
        ),
    ]
