# Generated by Django 5.2 on 2025-05-07 05:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("referee", "0004_alter_examination_candidate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referee",
            name="mobile",
            field=models.CharField(
                default="", max_length=25, verbose_name="Mobile phone number"
            ),
        ),
        migrations.AlterField(
            model_name="referee",
            name="phone",
            field=models.CharField(
                default="", max_length=25, verbose_name="Phone number"
            ),
        ),
    ]
