# Generated by Django 5.1.4 on 2024-12-23 15:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("helper", "0002_alter_location_address"),
        ("referee", "0003_refereerole_referee_mobile_referee_phone"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Accommodation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=240, verbose_name="Name of Accommodation"
                    ),
                ),
                (
                    "start",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Earliest Check-in"
                    ),
                ),
                (
                    "end",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Lates Check-out"
                    ),
                ),
                (
                    "type",
                    models.IntegerField(
                        choices=[
                            (0, "Private"),
                            (1, "Single room (surcharge)"),
                            (2, "Double room"),
                            (3, "Triple room"),
                            (10, "Single room"),
                            (11, "Dorm"),
                        ],
                        default=2,
                        verbose_name="Room Type",
                    ),
                ),
                ("info", models.TextField(blank=True, verbose_name="Information")),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="helper.address"
                    ),
                ),
            ],
            options={
                "verbose_name": "Accommodation",
                "verbose_name_plural": "Accommodations",
                "ordering": ["start", "end", "name"],
            },
        ),
        migrations.CreateModel(
            name="Competition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start", models.DateTimeField()),
                ("duration", models.DurationField()),
                (
                    "competition_fields",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MaxValueValidator(25),
                            django.core.validators.MinValueValidator(1),
                        ],
                    ),
                ),
                ("info", models.TextField(blank=True, verbose_name="Information")),
                (
                    "referees",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Number of Referees",
                    ),
                ),
                (
                    "observer",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(25),
                        ],
                        verbose_name="Number of Observers",
                    ),
                ),
                (
                    "application_open",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Registration Open"
                    ),
                ),
                (
                    "application_close",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Registration Close"
                    ),
                ),
                (
                    "application",
                    models.BooleanField(
                        default=True, verbose_name="Allow Registration"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "desired_level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="referee.refereelicense",
                    ),
                ),
                (
                    "head_referee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="referee.referee",
                    ),
                ),
                (
                    "invitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="referee.referee",
                    ),
                ),
                (
                    "minimum_level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="referee.refereelicense",
                    ),
                ),
            ],
            options={
                "verbose_name": "Competition",
                "verbose_name_plural": "Competitions",
                "ordering": ["start", "referees"],
            },
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "accommodation_arrival",
                    models.DateField(blank=True, null=True, verbose_name="Arrival Day"),
                ),
                (
                    "accommodation_departure",
                    models.DateField(
                        blank=True, null=True, verbose_name="Departure Day"
                    ),
                ),
                (
                    "accommodation_remark",
                    models.TextField(blank=True, verbose_name="Information"),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (-4, "No Show"),
                            (-3, "Declined"),
                            (-2, "Cancled"),
                            (-1, "Not selected"),
                            (0, "Applied"),
                            (1, "Selected"),
                            (2, "Invited"),
                            (3, "Participated"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "accommodation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="competition.accommodation",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="referee.refereerole",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="referee.referee",
                    ),
                ),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="Applications",
                        related_query_name="applications",
                        to="competition.competition",
                    ),
                ),
            ],
            options={
                "verbose_name": "Application",
                "verbose_name_plural": "Applicatoins",
                "order_with_respect_to": "user",
            },
        ),
        migrations.CreateModel(
            name="CompetitionCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="Name"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        related_query_name="child",
                        to="competition.competitioncategory",
                        verbose_name="next higher category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Competition CAtegory",
                "verbose_name_plural": "Competition Categories",
            },
        ),
        migrations.AddField(
            model_name="competition",
            name="category",
            field=models.ManyToManyField(
                to="competition.competitioncategory", verbose_name="Category"
            ),
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=240, verbose_name="Name")),
                ("start", models.DateTimeField()),
                ("end", models.DateTimeField(blank=True, default=None, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("info", models.TextField(blank=True, verbose_name="Information")),
                ("slug", models.SlugField(unique_for_year="start")),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="event_creator",
                        related_query_name="event_creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="helper.location",
                    ),
                ),
            ],
            options={
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
                "ordering": ["start", "end", "name"],
            },
        ),
        migrations.AddField(
            model_name="competition",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Competition",
                related_query_name="competition",
                to="competition.event",
            ),
        ),
        migrations.AddField(
            model_name="accommodation",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="competition.event"
            ),
        ),
        migrations.CreateModel(
            name="Invitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=240)),
                ("message", models.TextField(blank=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("sent", models.DateTimeField(blank=True, null=True)),
                (
                    "competition",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="competition.competition",
                        verbose_name="Invitation",
                    ),
                ),
                (
                    "invited",
                    models.ManyToManyField(
                        related_name="invitation",
                        related_query_name="invitation",
                        to="competition.application",
                        verbose_name="Invited",
                    ),
                ),
                (
                    "previous_invitation",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_invitation",
                        related_query_name="update",
                        to="competition.invitation",
                        verbose_name="previous invitation",
                    ),
                ),
                ("send_copy", models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["created", "sent"],
            },
        ),
    ]
